# Generated by Django 3.2.5 on 2021-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
